#!/bin/sh
# The next line is executed by /bin/sh, but not Tcl \
exec tclsh $0 $1

set EKTA10(name) "ekta10"

if {($argc != 1)} { 
  puts stderr "usage: $EKTA10(name) in.pgm"
  exit 
}

set infilename [lindex $argv 0]

if {![file exists $infilename]} {
  puts stderr "$EKTA10(name): file $infilename not found"
  exit 
} 

puts "processing file $infilename"

set EKTA10(initial) 20
set EKTA10(final) 200
set EKTA10(step) 5
set EKTA10(deltaniv) 10

set PINK "$env(PINK)"
#set env(path) "$PINK/bin;$env(path)"
set env(PATH) "$PINK/bin;$env(PATH)"
source "$PINK/tcl/my_exec.tcl"
source "$PINK/tcl/my_read.tcl"

# LINUX:
set PORTABLE(tmpdir) "/tmp"
# WINDOWS:
#set PORTABLE(tmpdir) "C:\\Tmp"

proc tmpfile {tmpname} {
  global EKTA10
  global PORTABLE
  return [file join $PORTABLE(tmpdir) "$EKTA10(name)_$tmpname"]
}

# calcule l'indice de deformabilite
#-----------------------------------
proc compute_index {seuil} {
  global EKTA10
  global infilename
  my_exec_q seuil $infilename $seuil [tmpfile 7]
  my_exec_q seuil $infilename [expr $seuil+$EKTA10(deltaniv)] [tmpfile 8]
 
  my_exec_q sub [tmpfile 7] [tmpfile 8] [tmpfile 9]
  my_exec_q pgm2list [tmpfile 9] b [tmpfile 10]
  set readtext [my_read_text [tmpfile 10]]
  set nbpoints [lindex $readtext 1]
  if {$nbpoints >= 20} {
    my_exec_q ellipseparams [tmpfile 10] [tmpfile 11]
    set readtext [my_read_text [tmpfile 11]]
    set ge [lindex $readtext 2]
    set pe [lindex $readtext 3]
    if {($ge >= 10) && ($ge <= 400) && ($pe >= 10) && ($pe <= 400)} {
      set ind [expr ($ge - $pe) / ($ge + $pe)]
      return $ind
    } else {
      return -1
    }
  } else {
    return -1
  }
}

puts "[expr $EKTA10(initial) - $EKTA10(step)] 0"
for {set k $EKTA10(initial)} {$k < $EKTA10(final)} {incr k $EKTA10(step)} {
  set i [compute_index $k]
  puts "$k $i"
}

#foreach file [glob -nocomplain [tmpfile "?"]] {
#  file delete -force $file
#}

#foreach file [glob -nocomplain [tmpfile "??"]] {
#  file delete -force $file
#}
