# This file will be configured to contain variables for CPack. These variables
# should be set in the CMake list file of the project before CPack module is
# included. The list of available CPACK_xxx variables and their associated
# documentation may be obtained using
#  cpack --help-variable-list
#
# Some variables are common to all generators (e.g. CPACK_PACKAGE_NAME)
# and some are specific to a generator
# (e.g. CPACK_NSIS_EXTRA_INSTALL_COMMANDS). The generator specific variables
# usually begin with CPACK_<GENNAME>_xxxx.


SET(CPACK_BINARY_BUNDLE "")
SET(CPACK_BINARY_CYGWIN "")
SET(CPACK_BINARY_DEB "")
SET(CPACK_BINARY_DRAGNDROP "")
SET(CPACK_BINARY_NSIS "")
SET(CPACK_BINARY_OSXX11 "")
SET(CPACK_BINARY_PACKAGEMAKER "")
SET(CPACK_BINARY_RPM "")
SET(CPACK_BINARY_STGZ "")
SET(CPACK_BINARY_TBZ2 "")
SET(CPACK_BINARY_TGZ "")
SET(CPACK_BINARY_TZ "")
SET(CPACK_BINARY_ZIP "")
SET(CPACK_CMAKE_GENERATOR "Unix Makefiles")
SET(CPACK_COMPONENT_UNSPECIFIED_HIDDEN "TRUE")
SET(CPACK_COMPONENT_UNSPECIFIED_REQUIRED "TRUE")
SET(CPACK_DEBIAN_PACKAGE_ARCHITECTURE "amd64")
SET(CPACK_DEBIAN_PACKAGE_DEPENDS "")
SET(CPACK_DEBIAN_PACKAGE_DESCRIPTION "Pink is an image processing library developed at ESIEE Engineering for research and teaching purposes. It contains implementations of over 200 algorithms for image segmentation and filtering. Most of the operators come from mathematical morphology, but it contains operators from different fields. It is a free software licensed under the  CeCILL license.")
SET(CPACK_DEBIAN_PACKAGE_MAINTAINER "Laszlo Marak <ujoimro@gmail.com>")
SET(CPACK_DEBIAN_PACKAGE_NAME "pink-image")
SET(CPACK_DEBIAN_PACKAGE_PRIORITY "optional")
SET(CPACK_DEBIAN_PACKAGE_RECOMMENDS "ipython")
SET(CPACK_DEBIAN_PACKAGE_SECTION "Productivity/Scientific/Other")
SET(CPACK_DEBIAN_PACKAGE_SUGGESTS "python-vtk")
SET(CPACK_DEBIAN_PACKAGE_VERSION "1.0.0")
SET(CPACK_GENERATOR "TBZ2;TGZ")
SET(CPACK_IGNORE_FILES "/tutorial/;/private/;~$;\\.svn;/TODO")
SET(CPACK_INSTALLED_DIRECTORIES "/home/odyssee/Projets/Pink/pink_lilian;/")
SET(CPACK_INSTALL_CMAKE_PROJECTS "")
SET(CPACK_INSTALL_PREFIX "/usr/local")
SET(CPACK_MODULE_PATH "")
SET(CPACK_NSIS_CONTACT "https://www.pinkhq.com")
SET(CPACK_NSIS_DISPLAY_NAME "Pink Image Processing Library")
SET(CPACK_NSIS_DISPLAY_NAME_SET "TRUE")
SET(CPACK_NSIS_INSTALLER_ICON_CODE "")
SET(CPACK_NSIS_INSTALLER_MUI_ICON_CODE "")
SET(CPACK_NSIS_INSTALL_ROOT "$PROGRAMFILES")
SET(CPACK_NSIS_PACKAGE_NAME "Pink Image Processing Library")
SET(CPACK_OUTPUT_CONFIG_FILE "/home/odyssee/Projets/Pink/pink_lilian/CPackConfig.cmake")
SET(CPACK_PACKAGE_DEFAULT_LOCATION "/")
SET(CPACK_PACKAGE_DESCRIPTION_FILE "/usr/share/cmake-2.8/Templates/CPack.GenericDescription.txt")
SET(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Pink Image")
SET(CPACK_PACKAGE_FILE_NAME "pink-image-1.0.0-Source")
SET(CPACK_PACKAGE_INSTALL_DIRECTORY "pink-image 1.0.0")
SET(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "pink-image 1.0.0")
SET(CPACK_PACKAGE_NAME "pink-image")
SET(CPACK_PACKAGE_RELOCATABLE "true")
SET(CPACK_PACKAGE_VENDOR "ProCarPlan s.r.o.")
SET(CPACK_PACKAGE_VERSION "1.0.0")
SET(CPACK_PACKAGE_VERSION_MAJOR "1")
SET(CPACK_PACKAGE_VERSION_MINOR "0")
SET(CPACK_PACKAGE_VERSION_PATCH "0")
SET(CPACK_RESOURCE_FILE_LICENSE "/home/odyssee/Projets/Pink/pink_lilian/CeCill_header.txt")
SET(CPACK_RESOURCE_FILE_README "/usr/share/cmake-2.8/Templates/CPack.GenericDescription.txt")
SET(CPACK_RESOURCE_FILE_WELCOME "/usr/share/cmake-2.8/Templates/CPack.GenericWelcome.txt")
SET(CPACK_RPM_PACKAGE_ARCHITECTURE "x86_64")
SET(CPACK_RPM_PACKAGE_DESCRIPTION "Pink is an image processing library developed at ESIEE Engineering for research and teaching purposes. It contains implementations of over 200 algorithms for image segmentation and filtering. Most of the operators come from mathematical morphology, but it contains operators from different fields. It is a free software licensed under the  CeCILL license.")
SET(CPACK_RPM_PACKAGE_GROUP "Productivity/Scientific/Other")
SET(CPACK_RPM_PACKAGE_LICENSE "CeCILL")
SET(CPACK_RPM_PACKAGE_NAME "pink-image")
SET(CPACK_RPM_PACKAGE_PROVIDES "pink-image-1.0")
SET(CPACK_RPM_PACKAGE_RELEASE "1")
SET(CPACK_RPM_PACKAGE_REQUIRES "")
SET(CPACK_RPM_PACKAGE_SUMMARY "Pink is an image processing library")
SET(CPACK_RPM_PACKAGE_VENDOR "ProCarPlan s.r.o.")
SET(CPACK_RPM_PACKAGE_VERSION "1.0.0")
SET(CPACK_SET_DESTDIR "OFF")
SET(CPACK_SOURCE_CYGWIN "")
SET(CPACK_SOURCE_GENERATOR "TBZ2;TGZ")
SET(CPACK_SOURCE_IGNORE_FILES "/tutorial/;/private/;~$;\\.svn;/TODO")
SET(CPACK_SOURCE_INSTALLED_DIRECTORIES "/home/odyssee/Projets/Pink/pink_lilian;/")
SET(CPACK_SOURCE_OUTPUT_CONFIG_FILE "/home/odyssee/Projets/Pink/pink_lilian/CPackSourceConfig.cmake")
SET(CPACK_SOURCE_PACKAGE_FILE_NAME "pink-image-1.0.0-Source")
SET(CPACK_SOURCE_TBZ2 "")
SET(CPACK_SOURCE_TGZ "")
SET(CPACK_SOURCE_TOPLEVEL_TAG "Linux-Source")
SET(CPACK_SOURCE_TZ "")
SET(CPACK_SOURCE_ZIP "")
SET(CPACK_STRIP_FILES "")
SET(CPACK_SYSTEM_NAME "Linux")
SET(CPACK_TOPLEVEL_TAG "Linux-Source")
