#!/bin/sh
USAGE="Usage: $0 in x y w h out"
if [ $# -gt 6 ]
then
	echo $USAGE
        exit
fi
if [ $# -lt 6 ]
then
	echo $USAGE
        exit
fi
ppm2pgm      $1 _$1.r _$1.g _$1.b
crop        _$1.r  $2  $3  $4  $5 _$1.r
crop        _$1.g  $2  $3  $4  $5 _$1.g
crop        _$1.b  $2  $3  $4  $5 _$1.b
pgm2ppm      _$1.r _$1.g _$1.b $6
rm          _$1.r _$1.g _$1.b

