#!/bin/sh
USAGE="Usage: $0 in param out"
if [ $# -gt 3 ]
then
	echo $USAGE
        exit
fi
if [ $# -lt 3 ]
then
	echo $USAGE
        exit
fi
medialaxis $1 0 0 $3
seuil2     $3 $2 255 0 255 $3
medialaxis $3 0 1 $3
seuil      $3 1 $3
