#!/bin/sh
USAGE="Usage: $0 in h out"
if [ $# -gt 3 ]
then
	echo $USAGE
        exit
fi
if [ $# -lt 3 ]
then
	echo $USAGE
        exit
fi
addconst     $1       -$2  _$1.sub
reconsdilat  _$1.sub  $1   vois4     $3
rm           _$1.sub

