#!/bin/sh
USAGE="Usage: $0 in outmin outmax"
if [ $# -gt 3 ]
then
	echo $USAGE
        exit
fi
if [ $# -lt 3 ]
then
	echo $USAGE
        exit
fi

convol $1 $HOME/Pink/masks/dir0_13x13.pgm _md
cp _md _mdmin
mv _md _mdmax

convol $1 $HOME/Pink/masks/dir1_13x13.pgm _md
min _md _mdmin _mdmin
max _md _mdmax _mdmax

convol $1 $HOME/Pink/masks/dir2_13x13.pgm _md
min _md _mdmin _mdmin
max _md _mdmax _mdmax

convol $1 $HOME/Pink/masks/dir3_13x13.pgm _md
min _md _mdmin _mdmin
max _md _mdmax _mdmax

convol $1 $HOME/Pink/masks/dir4_13x13.pgm _md
min _md _mdmin _mdmin
max _md _mdmax _mdmax

convol $1 $HOME/Pink/masks/dir5_13x13.pgm _md
min _md _mdmin _mdmin
max _md _mdmax _mdmax

convol $1 $HOME/Pink/masks/dir6_13x13.pgm _md
min _md _mdmin _mdmin
max _md _mdmax _mdmax

convol $1 $HOME/Pink/masks/dir7_13x13.pgm _md
min _md _mdmin $2
max _md _mdmax $3

rm _md
rm _mdmin
rm _mdmax
