#!/bin/sh
# ATTENTION : version valable seulement pour des elements structurants
# symetriques par rapport a l'origine
USAGE="Usage: $0 in elstruct xorig yorig zorig out"
if [ $# -gt 6 ]
then
	echo $USAGE
        exit
fi
if [ $# -lt 6 ]
then
	echo $USAGE
        exit
fi
erosbin3d    $1  $2  $3  $4  $5  _$1.eros
dilatbin3d  _$1.eros  $2  $3  $4  $5  $6
rm          _$1.eros
