#!/bin/sh
USAGE="Usage: $0 in seuilR seuilA out"
if [ $# -gt 4 ]
then
	echo $USAGE
        exit
fi
if [ $# -lt 4 ]
then
	echo $USAGE
        exit
fi
medialaxis $1 3 _m
seuil _m 1 _m1
skeleucl $1 8 _m1 _s

seuil _m $2 _ms
distc $1 3 _d
bisector _d _ms _a
seuil _a $3 _i
skeleton _s _d 8 _i $4