#!/bin/sh
USAGE="Usage: $0 in seuilR (in [1..infnty[) seuilA (in [0.001..pi]) out"
if [ $# -gt 4 ]
then
	echo $USAGE
        exit
fi
if [ $# -lt 4 ]
then
	echo $USAGE
        exit
fi
medialaxis $1 3 _m
echo "medialaxis done"
seuil _m $2 _ms
distc $1 3 _d
echo "distc done"
bisector _d _ms _a
echo "bisector done"
seuil _a $3 _i
skeleucl $1 26 _i $4
echo "skeleucl done"
